# Generated by Django 4.0.6 on 2022-07-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_customer_employee_orderemployee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderemployee',
            options={'ordering': ['-joint_date']},
        ),
    ]
