# Generated by Django 4.0.6 on 2022-07-29 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_alter_orderemployee_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='mypictures')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
