# Generated by Django 4.0.6 on 2022-07-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_dan_waktu', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dirham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_dan_waktu', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
